<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no">
<title>std::weak的抢红包 v2</title>
<link rel="stylesheet" href="/static/base.css">
</head>
<body>
{% block title %}
{% endblock %}
<div id="content_wrapper">
<article>
{% block content %}
{% endblock %}
</article>
</div>
<footer class="color1">
  <a class="color1 light" href="https://github.com/wacky6">
  rp_guess, Aries, (C) 2015, All rights reserved.
  </a>
</footer>
</body>
</html>
